export interface Recipe {
  id: string
  name: string
  category: string
  area: string
  instructions: string
  thumbnail: string
  ingredients: Array<{ name: string; measure: string }>
  tags: string[]
  cookTime: string
  difficulty: string
}

export const mockRecipes: Recipe[] = [
  {
    id: "1",
    name: "Margherita Pizza",
    category: "Italian",
    area: "Italian",
    instructions:
      "Preheat oven to 475°F. Roll out pizza dough on a floured surface. Spread tomato sauce evenly over the dough. Add fresh mozzarella slices. Drizzle with olive oil and season with salt. Bake for 12-15 minutes until crust is golden. Top with fresh basil leaves before serving.",
    thumbnail: "/margherita-pizza-with-fresh-basil-and-mozzarella.jpg",
    ingredients: [
      { name: "Pizza Dough", measure: "1 ball" },
      { name: "Tomato Sauce", measure: "1/2 cup" },
      { name: "Mozzarella", measure: "8 oz" },
      { name: "Fresh Basil", measure: "10 leaves" },
      { name: "Olive Oil", measure: "2 tbsp" },
    ],
    tags: ["Italian", "Pizza", "Vegetarian"],
    cookTime: "25 mins",
    difficulty: "Medium",
  },
  {
    id: "2",
    name: "Chicken Stir Fry",
    category: "Asian",
    area: "Chinese",
    instructions:
      "Cut chicken into bite-sized pieces. Heat oil in a wok over high heat. Add chicken and cook until golden. Remove chicken. Add vegetables and stir-fry for 3-4 minutes. Return chicken to wok. Add soy sauce and sesame oil. Toss everything together and serve over rice.",
    thumbnail: "/chicken-stir-fry-with-colorful-vegetables-in-wok.jpg",
    ingredients: [
      { name: "Chicken Breast", measure: "1 lb" },
      { name: "Bell Peppers", measure: "2 cups" },
      { name: "Soy Sauce", measure: "3 tbsp" },
      { name: "Sesame Oil", measure: "1 tbsp" },
      { name: "Garlic", measure: "3 cloves" },
    ],
    tags: ["Asian", "Stir Fry", "Quick"],
    cookTime: "20 mins",
    difficulty: "Easy",
  },
  {
    id: "3",
    name: "Chocolate Chip Cookies",
    category: "Dessert",
    area: "American",
    instructions:
      "Preheat oven to 375°F. Cream butter and sugars together. Beat in eggs and vanilla. Mix in flour, baking soda, and salt. Fold in chocolate chips. Drop spoonfuls onto baking sheet. Bake for 10-12 minutes until golden brown. Cool on wire rack.",
    thumbnail: "/golden-brown-chocolate-chip-cookies-on-cooling-rac.jpg",
    ingredients: [
      { name: "Butter", measure: "1 cup" },
      { name: "Brown Sugar", measure: "3/4 cup" },
      { name: "Eggs", measure: "2" },
      { name: "Flour", measure: "2 1/4 cups" },
      { name: "Chocolate Chips", measure: "2 cups" },
    ],
    tags: ["Dessert", "Cookies", "Baking"],
    cookTime: "30 mins",
    difficulty: "Easy",
  },
  {
    id: "4",
    name: "Caesar Salad",
    category: "Salad",
    area: "American",
    instructions:
      "Wash and chop romaine lettuce. Make dressing by whisking together mayo, lemon juice, garlic, and parmesan. Toss lettuce with dressing. Top with croutons and extra parmesan. Season with black pepper.",
    thumbnail: "/fresh-caesar-salad-with-croutons-and-parmesan.jpg",
    ingredients: [
      { name: "Romaine Lettuce", measure: "1 head" },
      { name: "Parmesan", measure: "1/2 cup" },
      { name: "Croutons", measure: "1 cup" },
      { name: "Caesar Dressing", measure: "1/2 cup" },
    ],
    tags: ["Salad", "Healthy", "Quick"],
    cookTime: "10 mins",
    difficulty: "Easy",
  },
  {
    id: "5",
    name: "Beef Tacos",
    category: "Mexican",
    area: "Mexican",
    instructions:
      "Brown ground beef in a skillet. Add taco seasoning and water. Simmer until thickened. Warm taco shells. Fill shells with beef. Top with lettuce, tomatoes, cheese, and sour cream.",
    thumbnail: "/beef-tacos-with-lettuce-cheese-and-toppings.jpg",
    ingredients: [
      { name: "Ground Beef", measure: "1 lb" },
      { name: "Taco Seasoning", measure: "2 tbsp" },
      { name: "Taco Shells", measure: "8" },
      { name: "Lettuce", measure: "2 cups" },
      { name: "Cheese", measure: "1 cup" },
    ],
    tags: ["Mexican", "Tacos", "Quick"],
    cookTime: "20 mins",
    difficulty: "Easy",
  },
  {
    id: "6",
    name: "Pancakes",
    category: "Breakfast",
    area: "American",
    instructions:
      "Mix flour, sugar, baking powder, and salt. In another bowl, whisk milk, egg, and melted butter. Combine wet and dry ingredients. Heat griddle and pour batter. Cook until bubbles form, then flip. Serve with maple syrup and butter.",
    thumbnail: "/stack-of-fluffy-pancakes-with-maple-syrup.jpg",
    ingredients: [
      { name: "Flour", measure: "2 cups" },
      { name: "Milk", measure: "1 1/2 cups" },
      { name: "Eggs", measure: "2" },
      { name: "Butter", measure: "1/4 cup" },
      { name: "Maple Syrup", measure: "to taste" },
    ],
    tags: ["Breakfast", "Pancakes", "Sweet"],
    cookTime: "20 mins",
    difficulty: "Easy",
  },
  {
    id: "7",
    name: "Greek Salad",
    category: "Salad",
    area: "Greek",
    instructions:
      "Chop tomatoes, cucumbers, and red onion. Add to a bowl with olives and feta cheese. Drizzle with olive oil and lemon juice. Season with oregano, salt, and pepper. Toss gently and serve.",
    thumbnail: "/greek-salad-with-feta-cheese-olives-and-tomatoes.jpg",
    ingredients: [
      { name: "Tomatoes", measure: "3" },
      { name: "Cucumber", measure: "1" },
      { name: "Feta Cheese", measure: "1 cup" },
      { name: "Olives", measure: "1/2 cup" },
      { name: "Olive Oil", measure: "3 tbsp" },
    ],
    tags: ["Salad", "Greek", "Healthy"],
    cookTime: "15 mins",
    difficulty: "Easy",
  },
  {
    id: "8",
    name: "Spaghetti Carbonara",
    category: "Italian",
    area: "Italian",
    instructions:
      "Cook spaghetti according to package directions. Fry bacon until crispy. Whisk eggs with parmesan. Drain pasta, reserving some water. Toss hot pasta with bacon. Remove from heat and quickly stir in egg mixture. Add pasta water to create creamy sauce. Season with black pepper.",
    thumbnail: "/creamy-spaghetti-carbonara-with-bacon-and-parmesan.jpg",
    ingredients: [
      { name: "Spaghetti", measure: "1 lb" },
      { name: "Bacon", measure: "8 slices" },
      { name: "Eggs", measure: "4" },
      { name: "Parmesan", measure: "1 cup" },
      { name: "Black Pepper", measure: "1 tsp" },
    ],
    tags: ["Italian", "Pasta", "Comfort Food"],
    cookTime: "25 mins",
    difficulty: "Medium",
  },
  {
    id: "9",
    name: "Pap and Wors",
    category: "South African",
    area: "South African",
    instructions:
      "Bring water to boil in a large pot with salt. Slowly add maize meal while stirring continuously to avoid lumps. Reduce heat to low, cover, and cook for 30 minutes, stirring occasionally. Meanwhile, grill boerewors over medium-high heat, turning frequently until cooked through and browned on all sides. Serve hot pap with grilled wors, tomato and onion relish, and chakalaka on the side.",
    thumbnail: "/south-african-pap-and-wors-with-tomato-relish.jpg",
    ingredients: [
      { name: "Maize Meal (Mealie Meal)", measure: "2 cups" },
      { name: "Water", measure: "4 cups" },
      { name: "Salt", measure: "1 tsp" },
      { name: "Boerewors", measure: "1 kg" },
      { name: "Butter", measure: "2 tbsp" },
      { name: "Tomatoes", measure: "2, diced" },
      { name: "Onions", measure: "1, diced" },
    ],
    tags: ["South African", "Traditional", "Braai"],
    cookTime: "45 mins",
    difficulty: "Easy",
  },
  {
    id: "10",
    name: "Kota (Quarter Loaf)",
    category: "South African",
    area: "South African",
    instructions:
      "Cut a quarter loaf of bread horizontally but not all the way through. Hollow out some of the bread from inside to create space for fillings. Spread butter or margarine inside. Layer with sliced polony or bologna. Add fried chips (french fries) inside the bread. Top with fried eggs, cheese slices, and Russian sausage or hot dog. Add sliced tomatoes, lettuce, and pickles. Drizzle with tomato sauce, mayonnaise, and peri-peri sauce. Close the bread and press down gently. Cut in half and serve immediately while hot.",
    thumbnail: "/south-african-kota-sandwich-with-chips-and-filling.jpg",
    ingredients: [
      { name: "Quarter Loaf Bread", measure: "1 loaf" },
      { name: "Butter", measure: "2 tbsp" },
      { name: "Polony/Bologna", measure: "6 slices" },
      { name: "French Fries", measure: "1 cup, fried" },
      { name: "Eggs", measure: "2, fried" },
      { name: "Cheese Slices", measure: "2" },
      { name: "Russian Sausage", measure: "1, fried" },
      { name: "Tomatoes", measure: "1, sliced" },
      { name: "Lettuce", measure: "2 leaves" },
      { name: "Pickles", measure: "3 slices" },
      { name: "Tomato Sauce", measure: "2 tbsp" },
      { name: "Mayonnaise", measure: "2 tbsp" },
      { name: "Peri-Peri Sauce", measure: "1 tbsp" },
    ],
    tags: ["South African", "Street Food", "Sandwich", "Fast Food"],
    cookTime: "30 mins",
    difficulty: "Easy",
  },
  {
    id: "11",
    name: "Bunny Chow",
    category: "South African",
    area: "South African",
    instructions:
      "Heat oil in a large pot and sauté onions until golden. Add garlic, ginger, curry powder, cumin, coriander, turmeric, and garam masala. Cook spices for 2 minutes. Add diced chicken or lamb and brown on all sides. Add tomatoes, potatoes, and water. Simmer for 45 minutes until meat is tender and curry is thick. Season with salt and pepper. Cut a loaf of white bread in half or quarters. Hollow out the inside, leaving the crust intact. Fill the hollowed bread with hot curry. Place the removed bread on top as a lid. Serve immediately with extra bread pieces for dipping.",
    thumbnail: "/south-african-bunny-chow-with-curry-filling.jpg",
    ingredients: [
      { name: "White Bread Loaf", measure: "1 loaf" },
      { name: "Chicken or Lamb", measure: "1 kg, diced" },
      { name: "Onions", measure: "2 large, diced" },
      { name: "Garlic", measure: "4 cloves, minced" },
      { name: "Ginger", measure: "2 tbsp, grated" },
      { name: "Curry Powder", measure: "3 tbsp" },
      { name: "Cumin", measure: "1 tsp" },
      { name: "Coriander", measure: "1 tsp" },
      { name: "Turmeric", measure: "1 tsp" },
      { name: "Garam Masala", measure: "1 tsp" },
      { name: "Tomatoes", measure: "400g can, crushed" },
      { name: "Potatoes", measure: "2, diced" },
      { name: "Oil", measure: "3 tbsp" },
    ],
    tags: ["South African", "Curry", "Street Food", "Durban"],
    cookTime: "75 mins",
    difficulty: "Medium",
  },
  {
    id: "12",
    name: "Bobotie",
    category: "South African",
    area: "South African",
    instructions:
      "Preheat oven to 180°C (350°F). Soak bread in milk and set aside. Sauté onions in butter until soft. Add garlic, curry powder, turmeric, and coriander. Cook for 2 minutes. Add ground beef or lamb and brown. Squeeze excess milk from bread and add bread to meat mixture. Add chutney, raisins, almonds, lemon juice, and bay leaves. Season with salt and pepper. Transfer to a greased baking dish. Beat eggs with remaining milk and pour over meat mixture. Bake for 45 minutes until golden and set. Serve with yellow rice, sambals, and chutney.",
    thumbnail: "/south-african-bobotie-with-yellow-rice.jpg",
    ingredients: [
      { name: "Ground Beef or Lamb", measure: "1 kg" },
      { name: "Onions", measure: "2, chopped" },
      { name: "Garlic", measure: "3 cloves, minced" },
      { name: "Curry Powder", measure: "2 tbsp" },
      { name: "Turmeric", measure: "1 tsp" },
      { name: "Bread Slices", measure: "2" },
      { name: "Milk", measure: "1 cup" },
      { name: "Eggs", measure: "2" },
      { name: "Chutney", measure: "2 tbsp" },
      { name: "Raisins", measure: "1/2 cup" },
      { name: "Almonds", measure: "1/4 cup, slivered" },
      { name: "Bay Leaves", measure: "2" },
      { name: "Lemon Juice", measure: "1 tbsp" },
    ],
    tags: ["South African", "Cape Malay", "Baked", "Traditional"],
    cookTime: "90 mins",
    difficulty: "Medium",
  },
  {
    id: "13",
    name: "Boerewors Roll",
    category: "South African",
    area: "South African",
    instructions:
      "Prepare a braai (grill) or heat a grill pan over medium-high heat. Coil the boerewors in a spiral shape and secure with a skewer if needed. Grill the boerewors for 15-20 minutes, turning frequently, until cooked through and nicely browned. Meanwhile, slice hot dog rolls lengthwise and lightly toast them on the grill. Place the grilled boerewors in the toasted roll. Top with caramelized onions, tomato and onion relish, or chakalaka. Drizzle with mustard or tomato sauce. Serve immediately while hot.",
    thumbnail: "/south-african-boerewors-roll-with-onions.jpg",
    ingredients: [
      { name: "Boerewors", measure: "500g" },
      { name: "Hot Dog Rolls", measure: "4" },
      { name: "Onions", measure: "2, sliced" },
      { name: "Butter", measure: "1 tbsp" },
      { name: "Mustard", measure: "to taste" },
      { name: "Tomato Sauce", measure: "to taste" },
    ],
    tags: ["South African", "Braai", "Street Food", "Fast Food"],
    cookTime: "25 mins",
    difficulty: "Easy",
  },
  {
    id: "14",
    name: "Chakalaka",
    category: "South African",
    area: "South African",
    instructions:
      "Heat oil in a large pot over medium heat. Sauté onions until soft and translucent. Add garlic, ginger, and curry powder. Cook for 2 minutes until fragrant. Add diced bell peppers, carrots, and cabbage. Stir-fry for 5 minutes. Add canned baked beans, tomatoes, and chili. Season with salt, pepper, and sugar. Simmer for 20-25 minutes, stirring occasionally, until vegetables are tender and flavors have melded. Adjust seasoning to taste. Serve hot or cold as a side dish with pap, bread, or braai meat.",
    thumbnail: "/south-african-chakalaka-vegetable-relish.jpg",
    ingredients: [
      { name: "Onions", measure: "2, diced" },
      { name: "Bell Peppers", measure: "2, diced" },
      { name: "Carrots", measure: "2, grated" },
      { name: "Cabbage", measure: "2 cups, shredded" },
      { name: "Baked Beans", measure: "400g can" },
      { name: "Tomatoes", measure: "400g can, diced" },
      { name: "Garlic", measure: "3 cloves, minced" },
      { name: "Ginger", measure: "1 tbsp, grated" },
      { name: "Curry Powder", measure: "2 tbsp" },
      { name: "Chili", measure: "1-2, chopped" },
      { name: "Oil", measure: "3 tbsp" },
    ],
    tags: ["South African", "Vegetarian", "Side Dish", "Spicy"],
    cookTime: "40 mins",
    difficulty: "Easy",
  },
  {
    id: "15",
    name: "Vetkoek",
    category: "South African",
    area: "South African",
    instructions:
      "Mix flour, salt, sugar, and instant yeast in a large bowl. Add warm water and oil. Mix until a soft dough forms. Knead for 5-10 minutes until smooth and elastic. Cover with a damp cloth and let rise in a warm place for 1 hour until doubled in size. Punch down dough and divide into golf ball-sized portions. Roll each portion into a ball. Heat oil in a deep pot to 180°C (350°F). Fry dough balls in batches for 3-4 minutes per side until golden brown and cooked through. Drain on paper towels. Serve hot, either sweet with honey, syrup, or jam, or savory with mince curry, cheese, or polony.",
    thumbnail: "/south-african-vetkoek-fried-bread.jpg",
    ingredients: [
      { name: "Flour", measure: "4 cups" },
      { name: "Instant Yeast", measure: "2 tsp" },
      { name: "Sugar", measure: "2 tbsp" },
      { name: "Salt", measure: "1 tsp" },
      { name: "Warm Water", measure: "1 1/2 cups" },
      { name: "Oil", measure: "2 tbsp + for frying" },
    ],
    tags: ["South African", "Fried", "Bread", "Traditional"],
    cookTime: "90 mins",
    difficulty: "Medium",
  },
  {
    id: "16",
    name: "Samp and Beans",
    category: "South African",
    area: "South African",
    instructions:
      "Soak samp and sugar beans overnight in separate bowls with plenty of water. Drain and rinse. In a large pot, combine samp and beans with fresh water. Bring to a boil, then reduce heat and simmer for 2-3 hours until tender, adding more water as needed. In a separate pan, sauté onions in butter until golden. Add garlic, curry powder, and tomatoes. Cook for 10 minutes. Add the onion mixture to the cooked samp and beans. Season with salt and pepper. Simmer for another 15 minutes to combine flavors. Serve hot as a side dish or main meal with meat or vegetables.",
    thumbnail: "/south-african-samp-and-beans-traditional-dish.jpg",
    ingredients: [
      { name: "Samp (Dried Corn)", measure: "2 cups" },
      { name: "Sugar Beans", measure: "1 cup" },
      { name: "Onions", measure: "2, chopped" },
      { name: "Garlic", measure: "3 cloves, minced" },
      { name: "Tomatoes", measure: "2, diced" },
      { name: "Butter", measure: "3 tbsp" },
      { name: "Curry Powder", measure: "1 tbsp" },
      { name: "Salt", measure: "to taste" },
      { name: "Black Pepper", measure: "to taste" },
    ],
    tags: ["South African", "Traditional", "Vegetarian", "Hearty"],
    cookTime: "180 mins",
    difficulty: "Medium",
  },
  {
    id: "17",
    name: "Mogodu (Tripe)",
    category: "South African",
    area: "South African",
    instructions:
      "Clean tripe thoroughly and cut into bite-sized pieces. Place tripe in a large pot with water and bring to a boil. Reduce heat and simmer for 2-3 hours until tender. Drain and set aside. In a large pot, heat oil and sauté onions until soft. Add garlic, ginger, curry powder, and tomatoes. Cook for 5 minutes. Add the cooked tripe, potatoes, and enough water to cover. Season with salt, pepper, and stock cubes. Simmer for 30-40 minutes until potatoes are tender and sauce has thickened. Serve hot with pap, rice, or dumplings.",
    thumbnail: "/south-african-mogodu-tripe-stew.jpg",
    ingredients: [
      { name: "Tripe", measure: "1 kg, cleaned" },
      { name: "Onions", measure: "2, chopped" },
      { name: "Garlic", measure: "4 cloves, minced" },
      { name: "Ginger", measure: "1 tbsp, grated" },
      { name: "Curry Powder", measure: "2 tbsp" },
      { name: "Tomatoes", measure: "400g can, diced" },
      { name: "Potatoes", measure: "3, diced" },
      { name: "Beef Stock Cubes", measure: "2" },
      { name: "Oil", measure: "3 tbsp" },
    ],
    tags: ["South African", "Traditional", "Stew", "Hearty"],
    cookTime: "240 mins",
    difficulty: "Hard",
  },
  {
    id: "18",
    name: "Magwinya (Fat Cakes)",
    category: "South African",
    area: "South African",
    instructions:
      "In a large bowl, mix flour, sugar, salt, and instant yeast. Add warm water gradually while mixing until a soft, sticky dough forms. Cover with a damp cloth and let rise for 45 minutes to 1 hour until doubled in size. Heat oil in a deep pot to 180°C (350°F). Wet your hands with water and pinch off small portions of dough. Shape into balls or flatten slightly. Carefully drop dough into hot oil. Fry for 2-3 minutes per side until golden brown and puffed up. Drain on paper towels. Serve hot with butter, jam, cheese, polony, or as a side with curry or stew.",
    thumbnail: "/south-african-magwinya-fat-cakes-fried-dough.jpg",
    ingredients: [
      { name: "Flour", measure: "4 cups" },
      { name: "Instant Yeast", measure: "2 tsp" },
      { name: "Sugar", measure: "3 tbsp" },
      { name: "Salt", measure: "1 tsp" },
      { name: "Warm Water", measure: "2 cups" },
      { name: "Oil", measure: "for deep frying" },
    ],
    tags: ["South African", "Fried", "Street Food", "Breakfast"],
    cookTime: "75 mins",
    difficulty: "Easy",
  },
  {
    id: "19",
    name: "Braai Sosaties",
    category: "South African",
    area: "South African",
    instructions:
      "Cut lamb or chicken into cubes. In a bowl, mix curry powder, turmeric, garlic, ginger, apricot jam, vinegar, and oil to make marinade. Add meat cubes and dried apricots to marinade. Mix well, cover, and refrigerate for at least 4 hours or overnight. Soak wooden skewers in water for 30 minutes. Thread marinated meat and apricots onto skewers, alternating with onion pieces. Prepare a braai (grill) to medium-high heat. Grill sosaties for 15-20 minutes, turning frequently and basting with remaining marinade, until meat is cooked through and caramelized. Serve hot with pap, rice, or salad.",
    thumbnail: "/south-african-braai-sosaties-skewers.jpg",
    ingredients: [
      { name: "Lamb or Chicken", measure: "1 kg, cubed" },
      { name: "Dried Apricots", measure: "1 cup" },
      { name: "Onions", measure: "2, cut into chunks" },
      { name: "Curry Powder", measure: "3 tbsp" },
      { name: "Turmeric", measure: "1 tsp" },
      { name: "Garlic", measure: "4 cloves, minced" },
      { name: "Ginger", measure: "2 tbsp, grated" },
      { name: "Apricot Jam", measure: "1/2 cup" },
      { name: "Vinegar", measure: "1/4 cup" },
      { name: "Oil", measure: "3 tbsp" },
    ],
    tags: ["South African", "Braai", "Skewers", "Marinated"],
    cookTime: "30 mins + marinating",
    difficulty: "Medium",
  },
  {
    id: "20",
    name: "Tomato Bredie",
    category: "South African",
    area: "South African",
    instructions:
      "Heat oil in a large pot and brown lamb pieces on all sides. Remove and set aside. In the same pot, sauté onions until soft. Add garlic, ginger, and spices (cinnamon, cardamom, cloves). Cook for 2 minutes. Add tomatoes, tomato paste, sugar, and bay leaves. Return lamb to pot. Add enough water to just cover the meat. Bring to a boil, then reduce heat and simmer covered for 1.5 hours. Add potatoes and continue simmering for another 30 minutes until meat is tender and potatoes are cooked. Season with salt and pepper. Serve hot with rice or pap.",
    thumbnail: "/south-african-tomato-bredie-lamb-stew.jpg",
    ingredients: [
      { name: "Lamb", measure: "1 kg, cubed" },
      { name: "Onions", measure: "2, chopped" },
      { name: "Garlic", measure: "4 cloves, minced" },
      { name: "Ginger", measure: "1 tbsp, grated" },
      { name: "Tomatoes", measure: "800g can, crushed" },
      { name: "Tomato Paste", measure: "2 tbsp" },
      { name: "Potatoes", measure: "4, quartered" },
      { name: "Cinnamon Stick", measure: "1" },
      { name: "Cardamom Pods", measure: "3" },
      { name: "Cloves", measure: "3" },
      { name: "Bay Leaves", measure: "2" },
      { name: "Sugar", measure: "1 tbsp" },
      { name: "Oil", measure: "3 tbsp" },
    ],
    tags: ["South African", "Stew", "Traditional", "Cape Malay"],
    cookTime: "150 mins",
    difficulty: "Medium",
  },
]

export const categories = [
  "All",
  "South African",
  "Indian",
  "African",
  "Italian",
  "Asian",
  "Mexican",
  "American",
  "Dessert",
  "Salad",
  "Breakfast",
  "British",
  "French",
  "Greek",
  "Japanese",
  "Thai",
  "Chinese",
  "Mediterranean",
  "Caribbean",
]

export const mockIngredients = [
  "Tomatoes",
  "Chicken",
  "Cheese",
  "Pasta",
  "Eggs",
  "Flour",
  "Butter",
  "Garlic",
  "Onions",
  "Bell Peppers",
  "Ground Beef or Lamb",
  "Potatoes",
  "Frozen Peas",
  "Ginger",
  "Curry Powder",
  "Spring Roll Wrappers",
  "Quarter Loaf Bread",
  "Polony/Bologna",
  "French Fries",
  "Russian Sausage",
  "Lettuce",
  "Pickles",
  "Tomato Sauce",
  "Mayonnaise",
  "Peri-Peri Sauce",
  "Maize Meal",
  "Boerewors",
  "Samp",
  "Sugar Beans",
  "Tripe",
  "Apricot Jam",
  "Lamb",
  "Chakalaka",
  "Chutney",
]
